name: 'First Interaction'

on:
    pull_request:
        types: [opened]
    issues:
        types: [opened]
    workflow_dispatch:

jobs:
    first-interaction:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - uses: actions/first-interaction@v3.1.0
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                issue_message: |
                    Thanks for opening this issue! We will look into it as soon as possible.
                pr_message: |
                    Thanks for opening this pull request! We will look into it as soon as possible.
